name:
  companionai
services:
  db:
    container_name: companion_db
    image: postgres
    env_file:
      - .env
    shm_size: 128mb
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /data/postgres
      POSTGRES_DB: companionai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 0s
  
  adminer:
    container_name: companion_adminer
    image: adminer
    env_file:
      - .env
    ports:
      - "8080:8080"

  api:
    container_name: companion_api
    depends_on:
      db: 
        condition: service_healthy
    build:
      context: ../
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      API_PORT: ${API_PORT}
      LLM_PORT: ${API_PORT}
      JWT_AUTH_METHOD: ${JWT_AUTH_METHOD}
    ports:
      - "${API_PORT}:${API_PORT}"
